sonar.projectKey=spydersoft-consulting_techradar-react-ui
sonar.javascript.lcov.reportPaths=./frontend/src/techradar-ui/output/coverage/lcov.info
sonar.sources=./frontend/src/techradar-ui/src/
sonar.exclusions=**/frontend/src/techradar-ui/src/api/**/*,**/frontend/src/Spydersoft.TechRadar.Frontend.*/**/*
sonar.test.inclusions=**/frontend/src/techradar-ui/src/**/*.test.tsx
sonar.scanner.scanAll=false
